MODEL:
  WEIGHT: "catalog://ImageNetPretrained/DLA34"
  # WEIGHT: "/media/wuminghu/work/model/SMOKE/oringe/model_final.pth"
  # WEIGHT: "/media/wuminghu/work/model/SMOKE/train/carla/model_0000400.pth"
INPUT:
  FLIP_PROB_TRAIN: 0.5
  SHIFT_SCALE_PROB_TRAIN: 0.3
DATASETS:
  # DETECT_CLASSES: ("Car", "Cyclist", "Pedestrian")
  DETECT_CLASSES: ("Car",)
  TRAIN: ("kitti_train",)
  # TEST: ("kitti_test",)
  TEST: ("kitti_train",)
  TRAIN_SPLIT: "train"
  # TEST_SPLIT: "test"
  TEST_SPLIT: "val"
SOLVER:
  # BASE_LR: 2.5e-4
  BASE_LR: 0.5e-4
  STEPS: (10000, 18000)
  # MAX_ITERATION: 25000
  MAX_ITERATION: 125000
  IMS_PER_BATCH: 6